- gatsby-config.js
- package.json
- yarn.lock
Adds gatsby analytics plugin and sets options.
> Update site to use analytics

- src/components/MainBanner/MainBanner.js
- src/components/SponsorCard/SponsorCard.js
- src/pages/sponsors/index.js
Updated Venue and HMB Logo Size as per Insertion Order.
> Updated Venue and HMB Logo

- src/components/layout.js
- src/pages/codeofconduct.mdx
- src/pages/communityevents.mdx
Included Events Page and Updated Nav Links
> Included Events Page

- src/pages/speakers.mdx
Changed typo for Christine and Changed Company Name for Vince.
> Speaker Corrections

- src/components/Hidden/index.js
- src/components/Speaker/Speaker.js
- src/components/Speaker/SpeakerModal.js
- src/pages/speakers.mdx
This page could benefit from some more attention (this addition is not necessarily ideal) but tried to make it a little more friendly for folks not using a mouse.
> Quick updates for speakers page

- src/components/Speaker/Speaker.js
- yarn.lock
This updates the `Learn More` button section.
It does the following:
* Moves the button out of the right columns and makes a new row under the main card content area
* Creates a new styled-component that wraps the standard button styles for appearance tweaks
* Updates the cursor on the card and the button area
> Update the learn more section on the speaker card

- src/pages/communityevents.mdx
Included Vue Columbus meetup group event and included mailing list subscribe links
> Updated Community Events page

- src/pages/communityevents.mdx
> Updated community events

- src/pages/communityevents.mdx
Updated links for Angular Meetup
> Update Angular Meetup

- src/components/MainBanner/MainBanner.js
- src/components/Schedule/index.js
- src/pages/index.js
- src/pages/schedule.mdx
Included Schedule Page and link to Schedule Page in Landing Page.
> Included Schedule Page

- src/components/layout.js
- src/pages/index.js
Moved Schedule Link to top level
> Moved Schedule link to top level

- src/pages/communityevents.mdx
> Community Events updated

- src/pages/callforsponsors.mdx
- src/pages/communityevents.mdx
Updated Sponsors page with link to prospectus and updated community events.
> Updated sponsors page with link

- src/pages/callforsponsors.mdx
Created Public Folder in GSuite. Added the prospectus to Public Folder and shared the file to external users.
> Update file link from Public Folder

- src/pages/communityevents.mdx
Updated October Community Events
> Updated October Community Events

- src/components/MainBanner/MainBanner.js
- src/pages/callforspeakers.mdx
- src/pages/communityevents.mdx
Updated CFP Pages to remove Sessionize links and remove Call for Speakers highlight text on Home Page.
> Updated CFP Pages

- src/pages/communityevents.mdx
> Added May Event

- src/pages/workshops.mdx
> Updated workshops

- src/pages/schedule/index.js
> Added sorting and filtering

- package-lock.json
- package.json
- src/content/schedule.json
- src/pages/schedule/index.js
I added quick timezone support to the schedule -- I kept getting confused! 😳 
It looks like the `<option>` menu selection isn't coming through in the gif, doh. It's the same option menu was the other two, for sort and track filter.
> Add timezone support to schedule
